version: '3.4'

services:  
  webfrontend:
    container_name: web
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile    
    ports:
        - "5050:80"
    depends_on:
        - webapi        

  webapi:
    container_name: api
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:        
        - seq
    ports:
        - "5051:80"

  webstatus:
    container_name: status
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: WebStatus/Dockerfile    
    ports:
        - "5052:80"
    depends_on:
        - webfrontend
        - webapi   

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
        - "5341:80"
    environment:
        - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
        - ./seq-data:/data