version: '3.4'

services:  
  webfrontend:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://0.0.0.0:80    
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile    
    ports:
        - "5050:80"
    depends_on:
        - webapi        

  webapi:    
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:        
        - seq
        - sqldata
    ports:
        - "5051:80"

  webstatus:    
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: WebStatus/Dockerfile    
    ports:
        - "5052:80"
    depends_on:
        - webfrontend
        - webapi

  seq:    
    image: datalust/seq:latest
    ports:
        - "5341:80"
    environment:
        - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
        - ./seq-data:/data

  sqldata:    
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"