version: '3.4'

services:
  webfrontend:
    container_name: web
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile    
    ports:
        - "5050:80"

  webapi:
    container_name: api
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
        - redis
        - seq
    ports:
        - "5051:80"

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
        - "6379:6379"

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
        - "5341:80"
    environment:
        - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
        - ./seq-data:/data

  rebrow:
    container_name: rebrow
    image: marian/rebrow
    ports:
        - "5001:5001"
    depends_on:
        - redis